name: Test Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-flask-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app
      run: |
        python -m flask --app ./app.py run &
        sleep 10
        curl -f http://127.0.0.1:5000 || exit 1
